dott_rides:
  outputs:
    dev:
      dataset: dott
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-central2
      method: oauth
      impersonate_service_account: create-infra@gfeledi-dott.iam.gserviceaccount.com
      priority: interactive
      project: gfeledi-dott
      threads: 4
      type: bigquery
    prod:
      dataset: dott
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-central2
      method: oauth
      impersonate_service_account: create-infra@gfeledi-dott.iam.gserviceaccount.com
      priority: interactive
      project: gfeledi-dott
      threads: 4
      type: bigquery
  target: prod
