steps:
  - id: 'build-from-repo'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REPO_IMAGE}', '.']
  - id: 'push-build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REPO_IMAGE}']
  - id: 'run-deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_SERVICE}', '--image', '${_REPO_IMAGE}', '--region', '${_REGION}', '--platform', 'managed', '--port', '8080', '--cpu', '1', '--memory', '512Mi', '--concurrency', '1', '--service-account', '${_SA_ID}', '--no-allow-unauthenticated', '--set-env-vars', 'TO_EMAILS=_TO_EMAILS', '--set-env-vars', 'SENDGRID_API_KEY=_SENDGRID_API_KEY']
  - id: 'policy-binding'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'services', 'add-iam-policy-binding', '${_SERVICE}', '--region', '${_REGION}', '--member', 'serviceAccount:${_SA_ID}', '--role', 'roles/run.invoker']
options:
  logging: CLOUD_LOGGING_ONLY
  #logsBucket: 'gs://build_logs_ici'
# substitutions:
#   _REPO_IMAGE: europe-central2-docker.pkg.dev/gfeledi-dott/gfeledi-repo/bq-load-dbt-img
#   _REGION: europe-central2
#   _SERVICE: telecharge-dbt-bq-svc
#   _SA_ID: create-infra@gfeledi-dott.iam.gserviceaccount.com
#   _TO_EMAILS: "adafeledi@gmail.com"
#   _SENDGRID_API_KEY: "maca"

substitutions:
  _REPO_IMAGE: europe-central2-docker.pkg.dev/gfeledi-dott/gfeledi-repo/bq-load-dbt-img
  _SA_ID: create-infra@gfeledi-dott.iam.gserviceaccount.com
  _REGION: europe-central2
